# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

#ToolInstaller
#Pipeline内でPower Platform Build Toolsを実行するためにまずはこれをやる
- task: PowerPlatformToolInstaller@2
  inputs:
    DefaultVersion: true

#Whoami
#Power Platform 開発環境への接続テスト
- task: PowerPlatformWhoAmi@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'PowerPlatform20250306'

#Power Platform内のすべてのカスタマイズを公開
- task: PowerPlatformPublishCustomizations@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'PowerPlatform20250306'
    AsyncOperation: true
    MaxAsyncWaitTime: '60'

#Export
#ソリューションをPower Platformの開発環境からExport
- task: PowerPlatformExportSolution@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'PowerPlatform20250306'
    SolutionName: 'METI'
    SolutionOutputFile: 'METI'
    AsyncOperation: true
    MaxAsyncWaitTime: '60'

#UnPack
#ソリューションをXMLファイルに展開
- task: PowerPlatformUnpackSolution@2
  inputs:
    SolutionInputFile: 'METI'
    SolutionTargetFolder: 'METI'

